name: spark_fs
version: 0.0.1
author: Alexander Ewetumo <trinoxf@gmail.com>
description: fs components for sparkflow
dependencies:
  sparkflow: any
  hub: any
  bass: any
  path: any
  spark_utils: any
  guardedfs: any
dependency_overrides:
  guardedfs:
     path: ../guardedfs
  sparkflow:
     path: ../sparkflow
  hub:
     path: ../hub
  bass:
     path: ../bass
  spark_utils:
     path: ../spark_utils
